<?php

str('COUNTRY_AFG', 'Afghanistan');
str('COUNTRY_ABW', 'Aruba');
str('COUNTRY_AGO', 'Angola');
str('COUNTRY_AIA', 'Anguilla');
str('COUNTRY_ALA', 'Aland');
str('COUNTRY_ALB', 'Albanie');
str('COUNTRY_AND', 'Andorre');
str('COUNTRY_ARE', 'Emirats arabes unis');
str('COUNTRY_ARG', 'Argentine');
str('COUNTRY_ARM', 'Arménie');
str('COUNTRY_ASM', 'Samoa américaines');
str('COUNTRY_ATA', 'Antarctique');
str('COUNTRY_ATF', 'Terres australes et antarctiques françaises');
str('COUNTRY_ATG', 'Antigua-et-Barbuda');
str('COUNTRY_AUS', 'Australie');
str('COUNTRY_AUT', 'Autriche');
str('COUNTRY_AZE', 'Azerbaïdjan');
str('COUNTRY_BDI', 'Burundi');
str('COUNTRY_BEL', 'Belgique');
str('COUNTRY_BEN', 'Bénin');
str('COUNTRY_BES', 'Bonaire, Saint-Eustache et Saba');
str('COUNTRY_BFA', 'Burkina Faso');
str('COUNTRY_BGD', 'Bangladesh');
str('COUNTRY_BGR', 'Bulgarie');
str('COUNTRY_BHR', 'Bahreïn');
str('COUNTRY_BHS', 'Bahamas');
str('COUNTRY_BIH', 'Bosnie-Herzégovine');
str('COUNTRY_BLM', 'Saint-Barthélemy');
str('COUNTRY_BLR', 'Biélorussie');
str('COUNTRY_BLZ', 'Belize');
str('COUNTRY_BMU', 'Bermudes');
str('COUNTRY_BOL', 'Bolivie');
str('COUNTRY_BRA', 'Brésil');
str('COUNTRY_BRB', 'Barbade');
str('COUNTRY_BRN', 'Brunei');
str('COUNTRY_BTN', 'Bhoutan');
str('COUNTRY_BVT', 'Ile Bouvet');
str('COUNTRY_BWA', 'Botswana');
str('COUNTRY_CAF', 'République centrafricaine');
str('COUNTRY_CAN', 'Canada');
str('COUNTRY_CCK', 'Iles Cocos');
str('COUNTRY_CHE', 'Suisse');
str('COUNTRY_CHL', 'Chili');
str('COUNTRY_CHN', 'Chine');
str('COUNTRY_CIV', 'Côte d\'Ivoire');
str('COUNTRY_CMR', 'Cameroun');
str('COUNTRY_COD', 'République démocratique du Congo');
str('COUNTRY_COG', 'République du Congo');
str('COUNTRY_COK', 'Iles Cook');
str('COUNTRY_COL', 'Colombie');
str('COUNTRY_COM', 'Comores ');
str('COUNTRY_CPV', 'Cap-Vert');
str('COUNTRY_CRI', 'Costa Rica');
str('COUNTRY_CUB', 'Cuba');
str('COUNTRY_CUW', 'Curaçao');
str('COUNTRY_CXR', 'Ile Christmas');
str('COUNTRY_CYM', 'Iles Caïmans');
str('COUNTRY_CYP', 'Chypre');
str('COUNTRY_CZE', 'République tchèque');
str('COUNTRY_DEU', 'Allemagne');
str('COUNTRY_DJI', 'Djibouti');
str('COUNTRY_DMA', 'Dominique');
str('COUNTRY_DNK', 'Danemark');
str('COUNTRY_DOM', 'République dominicaine');
str('COUNTRY_DZA', 'Algérie');
str('COUNTRY_ECU', 'Equateur');
str('COUNTRY_EGY', 'Egypte');
str('COUNTRY_ERI', 'Erythrée');
str('COUNTRY_ESH', 'Sahara occidental');
str('COUNTRY_ESP', 'Espagne');
str('COUNTRY_EST', 'Estonie');
str('COUNTRY_ETH', 'Ethiopie');
str('COUNTRY_FIN', 'Finlande');
str('COUNTRY_FJI', 'Fidji');
str('COUNTRY_FLK', 'Iles Malouines');
str('COUNTRY_FRA', 'France');
str('COUNTRY_FRO', 'Iles Féroé');
str('COUNTRY_FSM', 'Micronésie');
str('COUNTRY_GAB', 'Gabon');
str('COUNTRY_GBR', 'Royaume-Uni');
str('COUNTRY_GEO', 'Géorgie');
str('COUNTRY_GGY', 'Guernesey');
str('COUNTRY_GHA', 'Ghana');
str('COUNTRY_GIB', 'Gibraltar');
str('COUNTRY_GIN', 'Guinée');
str('COUNTRY_GLP', 'Guadeloupe');
str('COUNTRY_GMB', 'Gambie');
str('COUNTRY_GNB', 'Guinée-Bissau');
str('COUNTRY_GNQ', 'Guinée équatoriale');
str('COUNTRY_GRC', 'Grèce');
str('COUNTRY_GRD', 'Grenade');
str('COUNTRY_GRL', 'Groenland');
str('COUNTRY_GTM', 'Guatemala');
str('COUNTRY_GUF', 'Guyane Française');
str('COUNTRY_GUM', 'Guam');
str('COUNTRY_GUY', 'Guyane');
str('COUNTRY_HKG', 'Hong Kong');
str('COUNTRY_HMD', 'Iles Heard-et-MacDonald');
str('COUNTRY_HND', 'Honduras');
str('COUNTRY_HRV', 'Croatie');
str('COUNTRY_HTI', 'Haïti');
str('COUNTRY_HUN', 'Hongrie');
str('COUNTRY_IDN', 'Indonésie');
str('COUNTRY_IMN', 'Ile de Man');
str('COUNTRY_IND', 'Inde');
str('COUNTRY_IOT', 'Territoire britannique de l\'océan Indien');
str('COUNTRY_IRL', 'Irlande');
str('COUNTRY_IRN', 'Iran');
str('COUNTRY_IRQ', 'Irak');
str('COUNTRY_ISL', 'Islande');
str('COUNTRY_ISR', 'Israël');
str('COUNTRY_ITA', 'Italie');
str('COUNTRY_JAM', 'Jamaïque');
str('COUNTRY_JEY', 'Jersey');
str('COUNTRY_JOR', 'Jordanie');
str('COUNTRY_JPN', 'Japon');
str('COUNTRY_KAZ', 'Kazakhstan');
str('COUNTRY_KEN', 'Kenya');
str('COUNTRY_KGZ', 'Kirghizistan');
str('COUNTRY_KHM', 'Cambodge');
str('COUNTRY_KIR', 'Kiribati');
str('COUNTRY_KNA', 'Saint-Christophe-et-Niévès');
str('COUNTRY_KOR', 'Corée du Sud');
str('COUNTRY_KWT', 'Koweït');
str('COUNTRY_LAO', 'Laos');
str('COUNTRY_LBN', 'Liban');
str('COUNTRY_LBR', 'Liberia');
str('COUNTRY_LBY', 'Libye');
str('COUNTRY_LCA', 'Sainte-Lucie');
str('COUNTRY_LIE', 'Liechtenstein');
str('COUNTRY_LSO', 'Lesotho');
str('COUNTRY_LKA', 'Sri Lanka');
str('COUNTRY_LTU', 'Lituanie');
str('COUNTRY_LUX', 'Luxembourg');
str('COUNTRY_LVA', 'Lettonie');
str('COUNTRY_MAC', 'Macao');
str('COUNTRY_MAF', 'Saint-Martin (Antilles françaises)');
str('COUNTRY_MAR', 'Maroc');
str('COUNTRY_MCO', 'Monaco');
str('COUNTRY_MDA', 'Moldavie');
str('COUNTRY_MDG', 'Madagascar');
str('COUNTRY_MDV', 'Maldives');
str('COUNTRY_MEX', 'Mexique');
str('COUNTRY_MHL', 'Marshall');
str('COUNTRY_MKD', 'Macédoine');
str('COUNTRY_MLI', 'Mali');
str('COUNTRY_MLT', 'Malte');
str('COUNTRY_MMR', 'Birmanie');
str('COUNTRY_MNE', 'Monténégro');
str('COUNTRY_MNG', 'Mongolie');
str('COUNTRY_MNP', 'Iles Mariannes du Nord');
str('COUNTRY_MOZ', 'Mozambique');
str('COUNTRY_MRT', 'Mauritanie');
str('COUNTRY_MSR', 'Montserrat');
str('COUNTRY_MTQ', 'Martinique');
str('COUNTRY_MUS', 'Maurice ');
str('COUNTRY_MWI', 'Malawi');
str('COUNTRY_MYS', 'Malaisie');
str('COUNTRY_MYT', 'Mayotte');
str('COUNTRY_NAM', 'Namibie');
str('COUNTRY_NCL', 'Nouvelle-Calédonie');
str('COUNTRY_NER', 'Niger');
str('COUNTRY_NFK', 'Ile Norfolk');
str('COUNTRY_NGA', 'Nigeria');
str('COUNTRY_NIC', 'Nicaragua');
str('COUNTRY_NIU', 'Niue');
str('COUNTRY_NLD', 'Pays-Bas');
str('COUNTRY_NOR', 'Norvège');
str('COUNTRY_NPL', 'Népal');
str('COUNTRY_NRU', 'Nauru');
str('COUNTRY_NZL', 'Nouvelle-Zélande');
str('COUNTRY_OMN', 'Oman');
str('COUNTRY_PAK', 'Pakistan');
str('COUNTRY_PAN', 'Panama');
str('COUNTRY_PCN', 'Iles Pitcairn');
str('COUNTRY_PER', 'Pérou');
str('COUNTRY_PHL', 'Philippines');
str('COUNTRY_PLW', 'Palau');
str('COUNTRY_PNG', 'Papouasie-Nouvelle-Guinée');
str('COUNTRY_POL', 'Pologne');
str('COUNTRY_PRI', 'Puerto Rico');
str('COUNTRY_PRK', 'Corée du Nord');
str('COUNTRY_PRT', 'Portugal');
str('COUNTRY_PRY', 'Paraguay');
str('COUNTRY_PSE', 'Autorité palestinienne');
str('COUNTRY_PYF', 'Polynésie française');
str('COUNTRY_QAT', 'Qatar');
str('COUNTRY_REU', 'La Réunion');
str('COUNTRY_ROU', 'Roumanie');
str('COUNTRY_RUS', 'Russie');
str('COUNTRY_RWA', 'Rwanda');
str('COUNTRY_SAU', 'Arabie saoudite');
str('COUNTRY_SDN', 'Soudan');
str('COUNTRY_SEN', 'Sénégal');
str('COUNTRY_SGP', 'Singapour');
str('COUNTRY_SGS', 'Géorgie du Sud-et-les Iles Sandwich du Sud');
str('COUNTRY_SHN', 'Sainte-Hélène, Ascension et Tristan da Cunha');
str('COUNTRY_SJM', 'Svalbard et île Jan Mayen');
str('COUNTRY_SLB', 'Salomon');
str('COUNTRY_SLE', 'Sierra Leone');
str('COUNTRY_SLV', 'Salvador');
str('COUNTRY_SMR', 'Saint-Marin');
str('COUNTRY_SOM', 'Somalie');
str('COUNTRY_SPM', 'Saint-Pierre-et-Miquelon');
str('COUNTRY_SRB', 'Serbie');
str('COUNTRY_SSD', 'Soudan du Sud');
str('COUNTRY_SUR', 'Suriname');
str('COUNTRY_STP', 'Sao Tomé-et-Principe');
str('COUNTRY_SVK', 'Slovaquie');
str('COUNTRY_SVN', 'Slovénie');
str('COUNTRY_SWE', 'Suède');
str('COUNTRY_SWZ', 'Swaziland');
str('COUNTRY_SXM', 'Saint-Martin');
str('COUNTRY_SYC', 'Seychelles');
str('COUNTRY_SYR', 'Syrie');
str('COUNTRY_TCA', 'Iles Turques-et-Caïques');
str('COUNTRY_TCD', 'Tchad');
str('COUNTRY_THA', 'Thaïlande');
str('COUNTRY_TGO', 'Togo');
str('COUNTRY_TJK', 'Tadjikistan');
str('COUNTRY_TKL', 'Tokelau');
str('COUNTRY_TKM', 'Turkménistan');
str('COUNTRY_TLS', 'Timor oriental');
str('COUNTRY_TON', 'Tonga');
str('COUNTRY_TTO', 'Trinité-et-Tobago');
str('COUNTRY_TUN', 'Tunisie');
str('COUNTRY_TUR', 'Turquie');
str('COUNTRY_TUV', 'Tuvalu');
str('COUNTRY_TWN', 'Taïwan / (République de Chine (Taïwan))');
str('COUNTRY_TZA', 'Tanzanie');
str('COUNTRY_UGA', 'Ouganda');
str('COUNTRY_UKR', 'Ukraine');
str('COUNTRY_UMI', 'Iles mineures éloignées des États-Unis');
str('COUNTRY_URY', 'Uruguay');
str('COUNTRY_USA', 'Etats-Unis');
str('COUNTRY_UZB', 'Ouzbékistan');
str('COUNTRY_VAT', 'Saint-Siège (État de la Cité du Vatican)');
str('COUNTRY_VCT', 'Saint-Vincent-et-les-Grenadines');
str('COUNTRY_VEN', 'Venezuela');
str('COUNTRY_VGB', 'Iles Vierges britanniques');
str('COUNTRY_VIR', 'Iles Vierges des États-Unis');
str('COUNTRY_VNM', 'Viêt Nam');
str('COUNTRY_VUT', 'Vanuatu');
str('COUNTRY_WLF', 'Wallis-et-Futuna');
str('COUNTRY_WSM', 'Samoa');
str('COUNTRY_YEM', 'Yémen');
str('COUNTRY_ZAF', 'Afrique du Sud');
str('COUNTRY_ZMB', 'Zambie');

?>
