<?php

str(COUNTRY_ABW, 'Aruba');
str(COUNTRY_AFG, 'Afghanistan');
str(COUNTRY_AGO, 'Angola');
str(COUNTRY_AIA, 'Anguilla');
str(COUNTRY_ALA, 'Åland Islands');
str(COUNTRY_ALB, 'Albania');
str(COUNTRY_AND, 'Andorra');
str(COUNTRY_ANT, 'Netherlands Antilles');
str(COUNTRY_ARE, 'United Arab Emirates');
str(COUNTRY_ARG, 'Argentina');
str(COUNTRY_ARM, 'Armenia');
str(COUNTRY_ASM, 'American Samoa');
str(COUNTRY_ATA, 'Antarctica');
str(COUNTRY_ATF, 'French Southern Territories');
str(COUNTRY_ATG, 'Antigua and Barbuda');
str(COUNTRY_AUS, 'Australia');
str(COUNTRY_AUT, 'Austria');
str(COUNTRY_AZE, 'Azerbaijan');
str(COUNTRY_BDI, 'Burundi');
str(COUNTRY_BEL, 'Belgium');
str(COUNTRY_BEN, 'Benin');
str(COUNTRY_BES, 'Bonaire, Sint Eustatius and Saba');
str(COUNTRY_BFA, 'Burkina Faso');
str(COUNTRY_BGD, 'Bangladesh');
str(COUNTRY_BGR, 'Bulgaria');
str(COUNTRY_BHR, 'Bahrain');
str(COUNTRY_BHS, 'Bahamas');
str(COUNTRY_BIH, 'Bosnia and Herzegovina');
str(COUNTRY_BLM, 'Saint Barthélemy');
str(COUNTRY_BLR, 'Belarus');
str(COUNTRY_BLZ, 'Belize');
str(COUNTRY_BMU, 'Bermuda');
str(COUNTRY_BOL, 'Bolivia, Plurinational State of');
str(COUNTRY_BRA, 'Brazil');
str(COUNTRY_BRB, 'Barbados');
str(COUNTRY_BRN, 'Brunei Darussalam');
str(COUNTRY_BTN, 'Bhutan');
str(COUNTRY_BVT, 'Bouvet Island');
str(COUNTRY_BWA, 'Botswana');
str(COUNTRY_CAF, 'Central African Republic');
str(COUNTRY_CAN, 'Canada');
str(COUNTRY_CCK, 'Cocos (Keeling) Islands');
str(COUNTRY_CHE, 'Switzerland');
str(COUNTRY_CHL, 'Chile');
str(COUNTRY_CHN, 'China');
str(COUNTRY_CIV, 'Côte d\'Ivoire');
str(COUNTRY_CMR, 'Cameroon');
str(COUNTRY_COD, 'Congo, the Democratic Republic of the');
str(COUNTRY_COG, 'Congo');
str(COUNTRY_COK, 'Cook Islands');
str(COUNTRY_COL, 'Colombia');
str(COUNTRY_COM, 'Comoros');
str(COUNTRY_CPV, 'Cape Verde');
str(COUNTRY_CRI, 'Costa Rica');
str(COUNTRY_CUB, 'Cuba');
str(COUNTRY_CXR, 'Christmas Island');
str(COUNTRY_CYM, 'Cayman Islands');
str(COUNTRY_CYP, 'Cyprus');
str(COUNTRY_CZE, 'Czech Republic');
str(COUNTRY_DEU, 'Germany');
str(COUNTRY_DJI, 'Djibouti');
str(COUNTRY_DMA, 'Dominica');
str(COUNTRY_DNK, 'Denmark');
str(COUNTRY_DOM, 'Dominican Republic');
str(COUNTRY_DZA, 'Algeria');
str(COUNTRY_ECU, 'Ecuador');
str(COUNTRY_EGY, 'Egypt');
str(COUNTRY_ERI, 'Eritrea');
str(COUNTRY_ESH, 'Western Sahara');
str(COUNTRY_ESP, 'Spain');
str(COUNTRY_EST, 'Estonia');
str(COUNTRY_ETH, 'Ethiopia');
str(COUNTRY_FIN, 'Finland');
str(COUNTRY_FJI, 'Fiji');
str(COUNTRY_FLK, 'Falkland Islands (Malvinas)');
str(COUNTRY_FRA, 'France');
str(COUNTRY_FRO, 'Faroe Islands');
str(COUNTRY_FSM, 'Micronesia, Federated States of');
str(COUNTRY_GAB, 'Gabon');
str(COUNTRY_GBR, 'United Kingdom');
str(COUNTRY_GEO, 'Georgia');
str(COUNTRY_GGY, 'Guernsey');
str(COUNTRY_GHA, 'Ghana');
str(COUNTRY_GIB, 'Gibraltar');
str(COUNTRY_GIN, 'Guinea');
str(COUNTRY_GLP, 'Guadeloupe');
str(COUNTRY_GMB, 'Gambia');
str(COUNTRY_GNB, 'Guinea-Bissau');
str(COUNTRY_GNQ, 'Equatorial Guinea');
str(COUNTRY_GRC, 'Greece');
str(COUNTRY_GRD, 'Grenada');
str(COUNTRY_GRL, 'Greenland');
str(COUNTRY_GTM, 'Guatemala');
str(COUNTRY_GUF, 'French Guiana');
str(COUNTRY_GUM, 'Guam');
str(COUNTRY_GUY, 'Guyana');
str(COUNTRY_HKG, 'Hong Kong');
str(COUNTRY_HMD, 'Heard Island and McDonald Islands');
str(COUNTRY_HND, 'Honduras');
str(COUNTRY_HRV, 'Croatia');
str(COUNTRY_HTI, 'Haiti');
str(COUNTRY_HUN, 'Hungary');
str(COUNTRY_IDN, 'Indonesia');
str(COUNTRY_IMN, 'Isle of Man');
str(COUNTRY_IND, 'India');
str(COUNTRY_IOT, 'British Indian Ocean Territory');
str(COUNTRY_IRL, 'Ireland');
str(COUNTRY_IRN, 'Iran, Islamic Republic of');
str(COUNTRY_IRQ, 'Iraq');
str(COUNTRY_ISL, 'Iceland');
str(COUNTRY_ISR, 'Israel');
str(COUNTRY_ITA, 'Italy');
str(COUNTRY_JAM, 'Jamaica');
str(COUNTRY_JEY, 'Jersey');
str(COUNTRY_JOR, 'Jordan');
str(COUNTRY_JPN, 'Japan');
str(COUNTRY_KAZ, 'Kazakhstan');
str(COUNTRY_KEN, 'Kenya');
str(COUNTRY_KGZ, 'Kyrgyzstan');
str(COUNTRY_KHM, 'Cambodia');
str(COUNTRY_KIR, 'Kiribati');
str(COUNTRY_KNA, 'Saint Kitts and Nevis');
str(COUNTRY_KOR, 'Korea, Republic of');
str(COUNTRY_KWT, 'Kuwait');
str(COUNTRY_LAO, 'Lao People\'s Democratic Republic');
str(COUNTRY_LBN, 'Lebanon');
str(COUNTRY_LBR, 'Liberia');
str(COUNTRY_LBY, 'Libyan Arab Jamahiriya');
str(COUNTRY_LCA, 'Saint Lucia');
str(COUNTRY_LIE, 'Liechtenstein');
str(COUNTRY_LKA, 'Sri Lanka');
str(COUNTRY_LSO, 'Lesotho');
str(COUNTRY_LTU, 'Lithuania');
str(COUNTRY_LUX, 'Luxembourg');
str(COUNTRY_LVA, 'Latvia');
str(COUNTRY_MAC, 'Macao');
str(COUNTRY_MAF, 'Saint Martin (French part)');
str(COUNTRY_MAR, 'Morocco');
str(COUNTRY_MCO, 'Monaco');
str(COUNTRY_MDA, 'Moldova, Republic of');
str(COUNTRY_MDG, 'Madagascar');
str(COUNTRY_MDV, 'Maldives');
str(COUNTRY_MEX, 'Mexico');
str(COUNTRY_MHL, 'Marshall Islands');
str(COUNTRY_MKD, 'Macedonia, the former Yugoslav Republic of');
str(COUNTRY_MLI, 'Mali');
str(COUNTRY_MLT, 'Malta');
str(COUNTRY_MMR, 'Myanmar');
str(COUNTRY_MNE, 'Montenegro');
str(COUNTRY_MNG, 'Mongolia');
str(COUNTRY_MNP, 'Northern Mariana Islands');
str(COUNTRY_MOZ, 'Mozambique');
str(COUNTRY_MRT, 'Mauritania');
str(COUNTRY_MSR, 'Montserrat');
str(COUNTRY_MTQ, 'Martinique');
str(COUNTRY_MUS, 'Mauritius');
str(COUNTRY_MWI, 'Malawi');
str(COUNTRY_MYS, 'Malaysia');
str(COUNTRY_MYT, 'Mayotte');
str(COUNTRY_NAM, 'Namibia');
str(COUNTRY_NCL, 'New Caledonia');
str(COUNTRY_NER, 'Niger');
str(COUNTRY_NFK, 'Norfolk Island');
str(COUNTRY_NGA, 'Nigeria');
str(COUNTRY_NIC, 'Nicaragua');
str(COUNTRY_NIU, 'Niue');
str(COUNTRY_NLD, 'Netherlands');
str(COUNTRY_NOR, 'Norway');
str(COUNTRY_NPL, 'Nepal');
str(COUNTRY_NRU, 'Nauru');
str(COUNTRY_NZL, 'New Zealand');
str(COUNTRY_OMN, 'Oman');
str(COUNTRY_PAK, 'Pakistan');
str(COUNTRY_PAN, 'Panama');
str(COUNTRY_PCN, 'Pitcairn');
str(COUNTRY_PER, 'Peru');
str(COUNTRY_PHL, 'Philippines');
str(COUNTRY_PLW, 'Palau');
str(COUNTRY_PNG, 'Papua New Guinea');
str(COUNTRY_POL, 'Poland');
str(COUNTRY_PRI, 'Puerto Rico');
str(COUNTRY_PRK, 'Korea, Democratic People\'s Republic of');
str(COUNTRY_PRT, 'Portugal');
str(COUNTRY_PRY, 'Paraguay');
str(COUNTRY_PSE, 'Palestinian Territory, Occupied');
str(COUNTRY_PYF, 'French Polynesia');
str(COUNTRY_QAT, 'Qatar');
str(COUNTRY_REU, 'Réunion');
str(COUNTRY_ROU, 'Romania');
str(COUNTRY_RUS, 'Russian Federation');
str(COUNTRY_RWA, 'Rwanda');
str(COUNTRY_SAU, 'Saudi Arabia');
str(COUNTRY_SDN, 'Sudan');
str(COUNTRY_SEN, 'Senegal');
str(COUNTRY_SGP, 'Singapore');
str(COUNTRY_SGS, 'South Georgia and the South Sandwich Islands');
str(COUNTRY_SHN, 'Saint Helena, Ascension and Tristan da Cunha');
str(COUNTRY_SJM, 'Svalbard and Jan Mayen');
str(COUNTRY_SLB, 'Solomon Islands');
str(COUNTRY_SLE, 'Sierra Leone');
str(COUNTRY_SLV, 'El Salvador');
str(COUNTRY_SMR, 'San Marino');
str(COUNTRY_SOM, 'Somalia');
str(COUNTRY_SPM, 'Saint Pierre and Miquelon');
str(COUNTRY_SRB, 'Serbia');
str(COUNTRY_SSD, 'South Sudan');
str(COUNTRY_STP, 'Sao Tome and Principe');
str(COUNTRY_SUR, 'Suriname');
str(COUNTRY_SVK, 'Slovakia');
str(COUNTRY_SVN, 'Slovenia');
str(COUNTRY_SWE, 'Sweden');
str(COUNTRY_SWZ, 'Swaziland');
str(COUNTRY_SXM, 'Sint Maarten');
str(COUNTRY_SYC, 'Seychelles');
str(COUNTRY_SYR, 'Syrian Arab Republic');
str(COUNTRY_TCA, 'Turks and Caicos Islands');
str(COUNTRY_TCD, 'Chad');
str(COUNTRY_TGO, 'Togo');
str(COUNTRY_THA, 'Thailand');
str(COUNTRY_TJK, 'Tajikistan');
str(COUNTRY_TKL, 'Tokelau');
str(COUNTRY_TKM, 'Turkmenistan');
str(COUNTRY_TLS, 'Timor-Leste');
str(COUNTRY_TON, 'Tonga');
str(COUNTRY_TTO, 'Trinidad and Tobago');
str(COUNTRY_TUN, 'Tunisia');
str(COUNTRY_TUR, 'Turkey');
str(COUNTRY_TUV, 'Tuvalu');
str(COUNTRY_TWN, 'Taiwan, Province of China');
str(COUNTRY_TZA, 'Tanzania, United Republic of');
str(COUNTRY_UGA, 'Uganda');
str(COUNTRY_UKR, 'Ukraine');
str(COUNTRY_UMI, 'United States Minor Outlying Islands');
str(COUNTRY_URY, 'Uruguay');
str(COUNTRY_USA, 'United States');
str(COUNTRY_UZB, 'Uzbekistan');
str(COUNTRY_VAT, 'Holy See (Vatican City State)');
str(COUNTRY_VCT, 'Saint Vincent and the Grenadines');
str(COUNTRY_VEN, 'Venezuela, Bolivarian Republic of');
str(COUNTRY_VGB, 'Virgin Islands, British');
str(COUNTRY_VIR, 'Virgin Islands, U.S.');
str(COUNTRY_VNM, 'Viet Nam');
str(COUNTRY_VUT, 'Vanuatu');
str(COUNTRY_WLF, 'Wallis and Futuna');
str(COUNTRY_WSM, 'Samoa');
str(COUNTRY_YEM, 'Yemen');
str(COUNTRY_ZAF, 'South Africa');
str(COUNTRY_ZMB, 'Zambia');
str(COUNTRY_ZWE, 'Zimbabwe');

?>
