<?php

str(LOCATION_HOME, 'Home');
str(LOCATION_WORK, 'Work');

str(LOCATION_STREET_TYPE_AVENUE, 'Avenue');
str(LOCATION_STREET_TYPE_BOULEVARD, 'Boulevard');
str(LOCATION_STREET_TYPE_DRIVE, 'Drive');
str(LOCATION_STREET_TYPE_LANE, 'Lane');
str(LOCATION_STREET_TYPE_ROAD, 'Road');
str(LOCATION_STREET_TYPE_ROW, 'Row');
str(LOCATION_STREET_TYPE_STREEY, 'Street');
str(LOCATION_STREET_TYPE_WAY, 'Way');


?>