<?php

str(LOCATION_HOME, '家庭');
str(LOCATION_WORK, '工作');

str(LOCATION_STREET_TYPE_AVENUE, '大街');
str(LOCATION_STREET_TYPE_BOULEVARD, '大道');
str(LOCATION_STREET_TYPE_DRIVE, '驾驶');
str(LOCATION_STREET_TYPE_LANE, '巷');
str(LOCATION_STREET_TYPE_ROAD, '公路');
str(LOCATION_STREET_TYPE_ROW, '行');
str(LOCATION_STREET_TYPE_STREEY, '街');
str(LOCATION_STREET_TYPE_WAY, '路');


?>