<?php

str(PAYMENT_METHOD_BANK_CREDIT, '银行贷款');
str(PAYMENT_METHOD_BANK_PAYBOX, 'Paybox');
str(PAYMENT_METHOD_BANK_PAYPAL, 'PayPal');
str(PAYMENT_METHOD_BANK_PURSE, 'Bank purse');
str(PAYMENT_METHOD_BANK_TRANSFER, '银行汇款');
str(PAYMENT_METHOD_CARD, '信用卡');
str(PAYMENT_METHOD_CARD_AMEX, 'Amex卡');
str(PAYMENT_METHOD_CARD_CB, 'Cb卡');
str(PAYMENT_METHOD_CARD_JCB, 'JCB卡');
str(PAYMENT_METHOD_CARD_MAESTRO, 'Maestro卡');
str(PAYMENT_METHOD_CARD_MASTERCARD, '万事达卡');
str(PAYMENT_METHOD_CARD_VISA, 'Visa卡');
str(PAYMENT_METHOD_CASH, '现金');
str(PAYMENT_METHOD_CASH_ON_DELIVERY, '货到付款');
str(PAYMENT_METHOD_CASHIER_CREDIT, '应收账款');
str(PAYMENT_METHOD_CASHIER_DEPOSIT, '已收账单');
str(PAYMENT_METHOD_CHEQUE, '支票');
str(PAYMENT_METHOD_DISCOUNT, '折扣');
str(PAYMENT_METHOD_FREE, '免费');
str(PAYMENT_METHOD_PURCHASE_ORDER, '采购订单');
str(PAYMENT_METHOD_VOUCHER, '代金券');
str(PAYMENT_METHOD_VOUCHER_GIFT, '礼品券');
str(PAYMENT_METHOD_VOUCHER_LUNCHEON, '午餐券');

?>
