<?php

str(PAYMENT_METHOD_BANK_CREDIT, 'Crédit bancaire');
str(PAYMENT_METHOD_BANK_PAYBOX, 'Paybox');
str(PAYMENT_METHOD_BANK_PAYPAL, 'Paypal');
str(PAYMENT_METHOD_BANK_PURSE, 'Action');
str(PAYMENT_METHOD_BANK_TRANSFER, 'Virement bancaire');
str(PAYMENT_METHOD_CARD, 'Carte');
str(PAYMENT_METHOD_CARD_AMEX, 'Carte Amex');
str(PAYMENT_METHOD_CARD_CB, 'CB');
str(PAYMENT_METHOD_CARD_JCB, 'Carte JCB');
str(PAYMENT_METHOD_CARD_MAESTRO, 'Carte Maestro');
str(PAYMENT_METHOD_CARD_MASTERCARD, 'Carte Mastercard');
str(PAYMENT_METHOD_CARD_VISA, 'Carte Visa');
str(PAYMENT_METHOD_CASH, 'Espèces');
str(PAYMENT_METHOD_CASH_ON_DELIVERY, 'Espèces à la livraison');
str(PAYMENT_METHOD_CASHIER_CREDIT, 'Note de crédit');
str(PAYMENT_METHOD_CASHIER_DEPOSIT, 'Acompte');
str(PAYMENT_METHOD_CHEQUE, 'Chèque');
str(PAYMENT_METHOD_DISCOUNT, 'Remise');
str(PAYMENT_METHOD_FREE, 'Gratuité');
str(PAYMENT_METHOD_PURCHASE_ORDER, 'Achat');
str(PAYMENT_METHOD_VOUCHER, 'Bon de réduction');
str(PAYMENT_METHOD_VOUCHER_GIFT, 'Bon achat');
str(PAYMENT_METHOD_VOUCHER_LUNCHEON, 'Chèque déjeuner');

?>
