<?php

str(PAYMENT_METHOD_BANK_CREDIT, 'Bank credit');
str(PAYMENT_METHOD_BANK_PAYBOX, 'Bank paybox');
str(PAYMENT_METHOD_BANK_PAYPAL, 'Bank paypal');
str(PAYMENT_METHOD_BANK_PURSE, 'Bank purse');
str(PAYMENT_METHOD_BANK_TRANSFER, 'Bank transfer');
str(PAYMENT_METHOD_CARD, 'Card');
str(PAYMENT_METHOD_CARD_AMEX, 'Card Amex');
str(PAYMENT_METHOD_CARD_CB, 'Card Cb');
str(PAYMENT_METHOD_CARD_JCB, 'Card Jcb');
str(PAYMENT_METHOD_CARD_MAESTRO, 'Card Maestro');
str(PAYMENT_METHOD_CARD_MASTERCARD, 'Card Mastercard');
str(PAYMENT_METHOD_CARD_VISA, 'Card Visa');
str(PAYMENT_METHOD_CASH, 'Cash');
str(PAYMENT_METHOD_CASH_ON_DELIVERY, 'Cash on delivery');
str(PAYMENT_METHOD_CASHIER_CREDIT, 'Cashier credit');
str(PAYMENT_METHOD_CASHIER_DEPOSIT, 'Cashier deposit');
str(PAYMENT_METHOD_CHEQUE, 'Cheque');
str(PAYMENT_METHOD_DISCOUNT, 'Discount');
str(PAYMENT_METHOD_FREE, 'Free');
str(PAYMENT_METHOD_PURCHASE_ORDER, 'Purchase order');
str(PAYMENT_METHOD_VOUCHER, 'Voucher');
str(PAYMENT_METHOD_VOUCHER_GIFT, 'Voucher gift');
str(PAYMENT_METHOD_VOUCHER_LUNCHEON, 'Voucher luncheon');

?>
