<?php

str(INDIVIDUAL_RELATIVE_AUNT, '姑妈/姨妈');
str(INDIVIDUAL_RELATIVE_BROTHER, '兄弟');    
str(INDIVIDUAL_RELATIVE_BROTHER_IN_LAW, '姐夫/妹夫');  
str(INDIVIDUAL_RELATIVE_COUSIN, '[表]兄弟姊妹');
str(INDIVIDUAL_RELATIVE_DAUGHTER, '女儿');
str(INDIVIDUAL_RELATIVE_DAUGHTER_IN_LAW, '儿媳');
str(INDIVIDUAL_RELATIVE_FATHER, '父亲');
str(INDIVIDUAL_RELATIVE_FATHER_IN_LAW, '岳父/公公');
str(INDIVIDUAL_RELATIVE_MOTHER, '母亲');
str(INDIVIDUAL_RELATIVE_MOTHER_IN_LAW, '岳母/婆婆');
str(INDIVIDUAL_RELATIVE_NEPHEW, '外甥/侄子');
str(INDIVIDUAL_RELATIVE_NIECE, '外甥女/侄女');            
str(INDIVIDUAL_RELATIVE_SISTER, '姐妹');
str(INDIVIDUAL_RELATIVE_SISTER_IN_LAW, '嫂子/弟妹');
str(INDIVIDUAL_RELATIVE_SON, '儿子');
str(INDIVIDUAL_RELATIVE_SON_IN_LAW, '女婿');
str(INDIVIDUAL_RELATIVE_STEPBROTHER, '继兄弟');            
str(INDIVIDUAL_RELATIVE_STEPDAUGHTER, '继女');      
str(INDIVIDUAL_RELATIVE_STEPFATHER, '继父');  
str(INDIVIDUAL_RELATIVE_STEPMOTHER, '继母');      
str(INDIVIDUAL_RELATIVE_STEPSISTER, '继姐妹');
str(INDIVIDUAL_RELATIVE_STEPSON, '继子');    
str(INDIVIDUAL_RELATIVE_UNCLE, '叔叔/伯父/舅父/姑父/姨父');

?>