<?php

str(INDIVIDUAL_RELATIVE_AUNT, 'Aunt');
str(INDIVIDUAL_RELATIVE_BROTHER, 'Brother');	
str(INDIVIDUAL_RELATIVE_BROTHER_IN_LAW, 'Brother-in-law');	
str(INDIVIDUAL_RELATIVE_COUSIN, 'Cousin');
str(INDIVIDUAL_RELATIVE_DAUGHTER, 'Daughter');
str(INDIVIDUAL_RELATIVE_DAUGHTER_IN_LAW, 'Daughter-in-law');
str(INDIVIDUAL_RELATIVE_FATHER, 'Father');
str(INDIVIDUAL_RELATIVE_FATHER_IN_LAW, 'Father-in-law');
str(INDIVIDUAL_RELATIVE_MOTHER, 'Mother');
str(INDIVIDUAL_RELATIVE_MOTHER_IN_LAW, 'Mother-in-law');
str(INDIVIDUAL_RELATIVE_NEPHEW, 'Nephew');
str(INDIVIDUAL_RELATIVE_NIECE, 'Niece');			
str(INDIVIDUAL_RELATIVE_SISTER, 'Sister');
str(INDIVIDUAL_RELATIVE_SISTER_IN_LAW, 'Sister-in-law');
str(INDIVIDUAL_RELATIVE_SON, 'Son');
str(INDIVIDUAL_RELATIVE_SON_IN_LAW, 'Son-in-law');
str(INDIVIDUAL_RELATIVE_STEPBROTHER, 'Stepbrother');			
str(INDIVIDUAL_RELATIVE_STEPDAUGHTER, 'Stepdaughter');		
str(INDIVIDUAL_RELATIVE_STEPFATHER, 'Stepfather');	
str(INDIVIDUAL_RELATIVE_STEPMOTHER, 'Stepmother');		
str(INDIVIDUAL_RELATIVE_STEPSISTER, 'Stepsister');
str(INDIVIDUAL_RELATIVE_STEPSON, 'Stepson');	
str(INDIVIDUAL_RELATIVE_UNCLE, 'Uncle');

?>