<?php

str(INDIVIDUAL_RELATIVE_AUNT, 'Tante');
str(INDIVIDUAL_RELATIVE_BROTHER, 'Frère');	
str(INDIVIDUAL_RELATIVE_BROTHER_IN_LAW, 'Beau-frère');	
str(INDIVIDUAL_RELATIVE_COUSIN, 'Cousin');
str(INDIVIDUAL_RELATIVE_DAUGHTER, 'Fille');
str(INDIVIDUAL_RELATIVE_DAUGHTER_IN_LAW, 'Belle-fille');
str(INDIVIDUAL_RELATIVE_FATHER, 'Père');
str(INDIVIDUAL_RELATIVE_FATHER_IN_LAW, 'Beau-père');
str(INDIVIDUAL_RELATIVE_MOTHER, 'Mère');
str(INDIVIDUAL_RELATIVE_MOTHER_IN_LAW, 'Belle-mère');
str(INDIVIDUAL_RELATIVE_NEPHEW, 'Neveu');
str(INDIVIDUAL_RELATIVE_NIECE, 'Nièce');			
str(INDIVIDUAL_RELATIVE_SISTER, 'Soeur');
str(INDIVIDUAL_RELATIVE_SISTER_IN_LAW, 'Belle-soeur');
str(INDIVIDUAL_RELATIVE_SON, 'Fils');
str(INDIVIDUAL_RELATIVE_SON_IN_LAW, 'Beau-fils');
str(INDIVIDUAL_RELATIVE_STEPBROTHER, 'Demi-frère');			
str(INDIVIDUAL_RELATIVE_STEPDAUGHTER, 'Belle-fille');		
str(INDIVIDUAL_RELATIVE_STEPFATHER, 'Beau-père');	
str(INDIVIDUAL_RELATIVE_STEPMOTHER, 'Belle-mère');		
str(INDIVIDUAL_RELATIVE_STEPSISTER, 'Demi-soeur');
str(INDIVIDUAL_RELATIVE_STEPSON, 'Beau-fils');	
str(INDIVIDUAL_RELATIVE_UNCLE, 'Oncle');

?>